### ISSUE TITLE
put on lint tool.

### ISSUE THREAD

**Issue by lv7777** [WhiteHawk-taka/katari#2]
二人で書く（予定）なのでcpp用lintツールを入れましょう。
___
because we will writing code with two person, I think got bettor that using lint tool for cpp.

**Comment by WhiteHawk-taka** [comment]
Google uses relatively strict style guidelines for C++.
https://google.github.io/styleguide/cppguide.html

How about this lint tool.

**Comment by WhiteHawk-taka** [comment]
OK
This issue go to wiki
